// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vffisiuqyoygzxftlfjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZmlzaXVxeW95Z3p4ZnRsZmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTA0MzEsImV4cCI6MjA2MDI4NjQzMX0.n0kgfcY0_54vdJWlaDWAFmQ9KwO4Ceo8ZsXRC01sVOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);